### PR TITLE
Production 7.3

### PR DESCRIPTION
**Pull request by hliang71**
Choose one of the templates below:

# Fingerprint
This pull requests adds a fingerprint for <KIA - NIRO-EV - 2019 - EX>.

## Testing
1. Turn off openpilot in EON UI
2. Run the following command via ssh into EON
root@localhost:/data/openpilot/selfdrive/debug$ pkill -f controlsd ; PYTHONPATH=/data/openpilot python /data/openpilot/selfdrive/controls/controlsd.py
WARNING: linker: /data/openpilot/selfdrive/controls/lib/longitudinal_mpc/libmpc2.so: unused DT entry: type 0x1d arg 0x1ffd
pid 5125's current scheduling policy: SCHED_OTHERls/lib/longitudinal_mpc/libmpc1.so: unused DT entry: type 0x1d arg 0x1ffd
WARNING: linker: /data/openpilot/selfdrive/controls/lib/longitudinal_mpc/libmpc2.so: unused DT entry: type 0x1d arg 0x1ffd
pid 5125's current scheduling policy: SCHED_OTHERls/lib/longitudinal_mpc/libmpc1.so: unused DT entry: type 0x1d arg 0x1ffd
pid 5125's current scheduling priority: 0
pid 5125's new scheduling policy: SCHED_FIFO
pid 5125's new scheduling priority: 3
Waiting for CAN messages...
Using cached CarParams
VIN DEEV__ BMS 
**fingerprinted KIA NIRO EV 2020 PLATINUM**
{"event": "alert_add", "alert_type": "startupNoControl", "enabled": false}

3. Turn off openpilot in EON UI
4. Run the following command
root@localhost:/system/comma/home$ python /data/openpilot/selfdrive/debug/dump.py carParams

carParams: Reader was evicted, reconnecting

( logMonoTime = 1807419639827,
  valid = true,
  carParams = (
    carName = "hyundai",
    carFingerprint = "KIA NIRO EV 2020 PLATINUM",
    enableGasInterceptor = false,
    enableCruise = true,
    enableCamera = true,
    enableDsu = false,
    enableApgs = false,
    minEnableSpeed = -1,
    minSteerSpeed = 0,
    safetyModel = noOutput,
    safetyParam = 0,
    steerMaxBP = [0],
    steerMaxV = [1],
    gasMaxBP = [0],
    gasMaxV = [0.5],
    brakeMaxBP = [0, 20],
    brakeMaxV = [1, 0.8],
    mass = 1873,
    wheelbase = 2.7,
    centerToFront = 1.08,
    steerRatio = 13.73,
    steerRatioRear = 0,
    rotationalInertia = 3202.8044,
    tireStiffnessFront = 94774.5,
    tireStiffnessRear = 99879.453,
    longitudinalTuning = (
      kpBP = [0, 5, 35],
      kpV = [1.2, 0.8, 0.5],
      kiBP = [0, 35],
      kiV = [0.18, 0.12],
      deadzoneBP = [0],
      deadzoneV = [0] ),
    lateralTuning = (
      pid = (kpBP = [0], kpV = [0.25], kiBP = [0], kiV = [0.05], kf = 6e-05) ),
    steerLimitAlert = false,
    vEgoStopping = 0,
    directAccelControl = false,
    stoppingControl = true,
    startAccel = 0,
    steerRateCost = 0.5,
    steerControlType = torque,
    radarOffCan = false,
    steerActuatorDelay = 0.1,
    openpilotLongitudinalControl = true,
    carVin = "DEEV__ BMS \x00\x00\x00\x00\x00\x00",
    isPandaBlack = true,
    dashcamOnly = false,
    safetyModelPassive = silent,
    transmissionType = unknown,
    carFw = [],
    radarTimeStep = 0.05,
    communityFeature = false,
    steerLimitTimer = 0.8,
    fingerprintSource = can,
    mdpsBus = 0,
    sasBus = 0,
    sccBus = 0,
    autoLcaEnabled = 1 ) )

### CODE REVIEW

**Comment by hliang71** [comment]
Hi there, I'm new to openpilot and I'm not a Python developer neither. But I managed to get the fingerprint for my 2019 Kia Niro EV EX. Please take a look to see if this is useful.

**Comment by xx979xx** [comment]
I usually do not change anything in old branches as it is history now
 @hliang71 I would like to know why not work on HKG_community which is 0.7.6

**Comment by hliang71** [comment]
@xx979xx I saw some comments on discord board saying HKG_community is not working for kia niro ev. Not sure if that is still the case, anyway I will test it out to see it that works for me. I will close this PR and will submit another PR to HKG_community once it works for me.

**Comment by xx979xx** [comment]
I will add your fingerprint now
please inform me if you have any issue

**Pull request merged**
