### PR TITLE
kona ev elect_ems add

### PR DESCRIPTION
**Pull request by crwusiz**
Choose one of the templates below:

# Fingerprint
kona ev and kona hev

# Car support
This pull requests adds support for <Make - Model - Year - Trim>.

This is an explorer link to a drive with the stock system enabled: ...
This is an explorer link to a drive with openpilot system enabled: ...

# Feature
This pull requests adds feature X

## Description
Explain what the feature does

## Testing
Explain how the feature was tested. Either by the added unit tests, or what tests were performed while driving.

### CODE REVIEW

**Review by davidew98 — CHANGES_REQUESTED** [review]
if frame % 5 == 0 and self.car_fingerprint in [CAR.SONATA, CAR.PALISADE, CAR.SONATA_H, CAR.SANTA_FE, CAR.KIA_NIRO_EV]:
Shouldn't we include CAR.KONA_EV since the Niro is built on the Kona Platform, or does it not use 20 Hz?

**Comment by crwusiz** [comment]
> if frame % 5 == 0 and self.car_fingerprint in [CAR.SONATA, CAR.PALISADE, CAR.SONATA_H, CAR.SANTA_FE, CAR.KIA_NIRO_EV]:
> Shouldn't we include CAR.KONA_EV since the Niro is built on the Kona Platform, or does it not use 20 Hz?

kona ev lfa....carcontroller not added....cluster no error

**Comment by xx979xx** [comment]
thank you very much @crwusiz

**Comment by davidew98** [comment]
I'm assuming with this commit to HKG I should be able to load HKG on my Comma2 and it should work with no edits in my Kona EV, am I right?

**Comment by crwusiz** [comment]
> I'm assuming with this commit to HKG I should be able to load HKG on my Comma2 and it should work with no edits in my Kona EV, am I right?

yes...kona ev comma two test ok

**Pull request merged**
