### PR TITLE
7.5 dev

### PR DESCRIPTION
**Pull request by moreno7798**
Choose one of the templates below:

# Fingerprint
This pull requests adds a fingerprint for <Make - Model - Year - Trim>.

This is an explorer link to a drive with the stock system enabled: ...

# Car support
This pull requests adds support for <Make - Model - Year - Trim>.

This is an explorer link to a drive with the stock system enabled: ...
This is an explorer link to a drive with openpilot system enabled: ...

# Feature
This pull requests adds feature X

## Description
Explain what the feature does

## Testing
Explain how the feature was tested. Either by the added unit tests, or what tests were performed while driving.

### CODE REVIEW

**Comment by moreno7798** [comment]
7.5

**Comment by xx979xx** [comment]
Hi, I see you have replace Optima. why is that?

**Comment by moreno7798** [comment]
From our last conversation we decided we'd wait for firgerprinting 2.0....
Optima and Sportage have identical fingerprints. So, in 7.3 to make it work on the Sportage I had to replace any instance of Optima in the code with Sportage. This worked in 7.3 but now that I'm testing 7.5 it is not working even after I do the code changes. Still testing as I installed 7.5-dev last night. Any idea why it may not work in 7.5?

**Comment by xx979xx** [comment]
7.5-dev is under development currently, and has many bugs
Idk

**Pull request closed without merging**
