### PR TITLE
add 2019 kia forte to readme

### PR DESCRIPTION
**Pull request by AskAlice**
the fingerprints are identical so there is no need to shim it in. The tuning works decently as-is

### CODE REVIEW

**Comment by maucoen** [comment]
quick question, which trim of Kia Forte works? having a hard time understanding what is standard on the 2019 and 2018.

**Comment by AskAlice** [comment]
@maucoen I am using probably the lowest trim possible. It has LKAS but no SCC. Same with the 2018. My vehicle was a rental so I'm not entirely sure of its exact model but... It's pretty lackluster in terms of what is equipped

**Comment by maucoen** [comment]
@AskAlice got it thanks! did you build the harness yourself?

**Comment by AskAlice** [comment]
@maucoen @BillS13iv built my KET giraffe. I built an MDPS giraffe for development, and because I wanted fallback on access to the messaging bus, but it's not necessary for full functionality at the moment or in the foreseeable future.

**Pull request merged**
