### PR TITLE
fix for mdps harness

### PR DESCRIPTION
**Pull request by s70160**

### CODE REVIEW

**Comment by xx979xx** [comment]
Hi
this is causing issue for C2, I would like to add a check for mdps harrness

**Comment by s70160** [comment]
I'm eon user.when I work the fork,I must added.If you can try it,pleases try eon and comma 2

**Comment by xx979xx** [comment]
try this fix 
in openpilot/panda/board/main.c  change line 151 to:
` if (mode_copy == SAFETY_ALLOUTPUT || mode_copy == SAFETY_HYUNDAI_LEGACY || mode_copy == SAFETY_HYUNDAI) {`

**Comment by xx979xx** [comment]
this is the check in 7.8-dev
https://github.com/xx979xx/openpilot/commit/05dfe31b32b6d802d7b42a391b4c21db04365fce

**Comment by xx979xx** [comment]
I think I fixed harness issue today
feel free to open this if you still have this issue

**Pull request closed without merging**
